import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createGame } from "../../../src/engine/setup";
import { beginGame } from "../../../src/engine/turn";
import { advanceCampaignWeek } from "../../../src/engine/campaignWeek";
import { createUkGame, ukAdvanceTurn, playablePartiesIn as ukParties } from "../../../src/engine/ukGame";
import { createCountryGame, countryAdvanceTurn, playablePartiesIn } from "../../../src/engine/countryGame";
import { COUNTRIES } from "../../../src/content/countries";
import { initUsReplayLog, recordUsWeek } from "../../../src/store/usReplay";
import { initUkReplayLog, recordUkWeek } from "../../../src/store/ukReplay";
import { initCountryReplayLog, recordCountryWeek } from "../../../src/store/countryReplay";
import { deriveReport } from "../../../src/lib/replay";

const vectors = [];
for (const player of ["dem", "rep"] as const) {
  const seed = player === "dem" ? "daily-2026-09-30" : "replay-us-republican";
  const mode = player === "dem" ? "daily" as const : "casual" as const;
  const election = player === "dem" ? "2024" : "2008";
  let game = beginGame(createGame({seed, scenario: election, playerCandidate: player, difficulty: "hard"}));
  let log = initUsReplayLog(game, mode);
  let steps = 0;
  while (game.phase !== "result") {
    if (steps++ > 20) throw new Error(`U.S. replay campaign did not finish: ${player}`);
    game.queuedActions = [{ type: "rally", candidate: player, stateId: "PA", day: 1 },
      { type: "fundraise", candidate: player, day: 2 }];
    const next = advanceCampaignWeek(game, "hard");
    log = recordUsWeek(log, game, next);
    game = next;
  }
  vectors.push({country: "US", election, player, seed, mode, log, report: deriveReport(log)});
}
for (const [id, election] of [["UK", "2024"], ["CA", "2021"], ["DE", "2025"], ["FR", "2022"], ["AU", "2025"]]) {
  const country = COUNTRIES[id];
  const player = (id === "UK" ? ukParties(election) : playablePartiesIn(country, election)).at(-1)!;
  const seed = `replay-${id}`;
  let game = id === "UK" ? createUkGame({seed, election, playerParty: player}) : createCountryGame(country, {seed, election, playerParty: player});
  let log = id === "UK" ? initUkReplayLog(game, "casual") : initCountryReplayLog(game, country, "casual");
  let steps = 0;
  while (game.phase !== "result") {
    if (steps++ > 20) throw new Error(`Replay campaign did not finish: ${id}`);
    game.queuedActions = [{type: "fundraise", party: player, day: 1}];
    const next = id === "UK" ? ukAdvanceTurn(game, {autoResolvePlayerEvents: true}) : countryAdvanceTurn(game, country, {autoResolvePlayerEvents: true});
    log = id === "UK" ? recordUkWeek(log, game, next) : recordCountryWeek(log, game, next, country);
    game = next;
  }
  vectors.push({country: id, election, player, seed, mode: "casual", log, report: deriveReport(log)});
}
const raw = JSON.stringify(vectors);
const characters = Array.from(raw);
const chunks = [];
for (let index = 0; index < characters.length; index += 10000) chunks.push(characters.slice(index, index + 10000).join(""));
const output = `// Generated by apps/native/scripts/export-replay-vectors.ts. Do not edit.\npackage com.lakesidegames.electioneer.engine\n\ninternal val REPLAY_WEB_VECTORS = listOf(\n${chunks.map(chunk => `    """${chunk}"""`).join(",\n")}\n).joinToString("")\n`;
const destination = new URL("../shared/src/commonTest/kotlin/com/lakesidegames/electioneer/engine/ReplayWebVectors.kt", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(fileURLToPath(destination), "utf8") !== output) throw new Error("Native replay fixtures differ from web. Regenerate and verify campaign reports.");
} else writeFileSync(fileURLToPath(destination), output);
console.log(`Verified ${vectors.length} full web replay logs and campaign reports across all six countries.`);
