import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createUkGame, projectUk, playablePartiesIn as ukParties } from "../../../src/engine/ukGame";
import { createCountryGame, projectCountry, playablePartiesIn } from "../../../src/engine/countryGame";
import { COUNTRIES } from "../../../src/content/countries";
import { movSeatAskSnapshot } from "../../../src/lib/ask";

const vectors = [];
for (const [id, election] of [["UK", "2024"], ["CA", "2021"], ["DE", "2025"], ["FR", "2022"], ["AU", "2025"]]) {
  const country = COUNTRIES[id];
  const parties = id === "UK" ? ukParties(election) : playablePartiesIn(country, election);
  for (const player of [parties[0], parties.at(-1)!]) {
    const seed = `ask-${id}-${player}`;
    const game = id === "UK" ? createUkGame({ seed, election, playerParty: player })
      : createCountryGame(country, { seed, election, playerParty: player });
    const target = game.regions.find(region => (region.baselineSeats?.[player] ?? 0) > 0) ?? game.regions[0];
    for (const planned of [false, true]) {
      if (planned) game.queuedActions = [{ type: "rally", party: player, regionId: target.id, day: 1 },
        { type: "fundraise", party: player, day: 2 }];
      const projection = id === "UK" ? projectUk(game) : projectCountry(game, country);
      vectors.push({ country: id, election, player, seed, target: target.id, planned,
        snapshot: movSeatAskSnapshot(game, projection, id === "UK" ? "UK" : country.label) });
    }
  }
}
const raw = JSON.stringify(vectors);
const characters = Array.from(raw);
const chunks = [];
for (let index = 0; index < characters.length; index += 10000) chunks.push(characters.slice(index, index + 10000).join(""));
const output = `// Generated by apps/native/scripts/export-ask-vectors.ts. Do not edit.\npackage com.lakesidegames.electioneer.engine\n\ninternal val ASK_SEAT_WEB_VECTORS = listOf(\n${chunks.map(chunk => `    """${chunk}"""`).join(",\n")}\n).joinToString("")\n`;
const destination = new URL("../shared/src/commonTest/kotlin/com/lakesidegames/electioneer/engine/AskSeatWebVectors.kt", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(fileURLToPath(destination), "utf8") !== output) throw new Error("Native Ask snapshots differ from web. Regenerate the campaign handoff fixtures.");
} else writeFileSync(fileURLToPath(destination), output);
console.log(`Verified ${vectors.length} web Ask snapshots across all five seat-based engines.`);
