import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createGame } from "../../../src/engine/setup";
import { advanceCampaignWeek } from "../../../src/engine/campaignWeek";
import { computeResult } from "../../../src/engine/voteModel";

let game = createGame({seed: "web-save-interchange", scenario: "2008", playerCandidate: "rep", difficulty: "hard", staff: ["field_director"]});
for (let week = 0; week < 4; week++) game = advanceCampaignWeek(game, "hard");
const raw = JSON.stringify(game);
const next = advanceCampaignWeek(game, "hard");
const result = computeResult(next);
const expected = JSON.stringify({seed: game.seed, turn: next.turn, rng: next.rngState,
  ev: result.electoralVotes, share: result.popularShare, cash: next.resources.rep.cash});
// Split UTF-16-safe chunks well below the JVM constant's 64KB UTF-8 limit.
const chars = Array.from(raw);
const chunks = [];
for (let i = 0; i < chars.length; i += 10000) chunks.push(chars.slice(i, i + 10000).join(""));
const output = `// Generated by apps/native/scripts/export-save-vector.ts. Do not edit.\npackage com.lakesidegames.electioneer.engine\n\ninternal val RAW_WEB_SAVE = listOf(\n${chunks.map(s => `    """${s}"""`).join(",\n")}\n).joinToString("")\ninternal val RAW_WEB_SAVE_NEXT = """${expected}"""\n`;
const destination = new URL("../shared/src/commonTest/kotlin/com/lakesidegames/electioneer/engine/RawWebSave.kt", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(fileURLToPath(destination), "utf8") !== output) throw new Error("Native raw save fixture differs from web. Regenerate and verify interchange.");
} else writeFileSync(fileURLToPath(destination), output);
console.log(`Verified web save interchange fixture (${Buffer.byteLength(raw)} bytes).`);
