// Expectations use the complete web campaign week, including client policy.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createGame } from "../../../src/engine/setup";
import { advanceCampaignWeek } from "../../../src/engine/campaignWeek";
import { projectElection, computeResult } from "../../../src/engine/voteModel";
import { getScenario } from "../../../src/content/scenarios";

const vectors = [];
for (const player of ["dem", "rep"] as const) {
  for (const difficulty of ["easy", "normal", "hard"] as const) {
    const scenario = player === "dem" ? "2024" : "2008";
    const ticket = getScenario(scenario)[player];
    const mate = ticket.runningMates.find(m => m.historical)!;
    const seed = "daily-2026-09-30";
    const staff = ["field_director", "media_guru", "veteran_manager"];
    let game = createGame({seed, scenario, playerCandidate: player, difficulty, staff, runningMate: mate.id});
    const weeks = [];
    while (game.phase !== "result") {
      // Dated setup actions exercise queued bonuses alongside the rival AI.
      game.queuedActions = [
        {type: "rally", candidate: player, stateId: "PA", day: 1},
        {type: "advertise", candidate: player, stateId: "PA", adMode: "positive", spend: 1_000_000, day: 2},
        {type: "fundraise", candidate: player, day: 3},
      ];
      game = advanceCampaignWeek(game, difficulty);
      const projection = projectElection(game);
      weeks.push({turn: game.turn, phase: game.phase, rng: game.rngState, ev: projection.ev,
        popular: computeResult(game).popularShare, resources: game.resources[player], staff: game.staff?.[player] ?? [],
        recap: game.lastRecap.map(({label, detail}) => ({label, detail})),
        result: game.result ? {electoralVotes: game.result.electoralVotes, popularShare: game.result.popularShare} : null});
    }
    vectors.push({player, difficulty, scenario, mate: mate.id, seed, staff, weeks});
  }
}
if (!vectors.some(v => v.weeks.some(w => w.staff.length < v.staff.length))) {
  throw new Error("Campaign vectors must exercise staff resignations.");
}
const destination = new URL("../shared/src/commonTest/kotlin/com/lakesidegames/electioneer/engine/CampaignWebVectors.kt", import.meta.url);
const output = `// Generated by apps/native/scripts/export-campaign-vectors.ts. Do not edit.\npackage com.lakesidegames.electioneer.engine\n\ninternal val CAMPAIGN_WEB_VECTORS = listOf(\n${vectors.map(v => `    """${JSON.stringify(v)}"""`).join(",\n")}\n).joinToString(",", "[", "]")\n`;
if (process.argv.includes("--check")) {
  if (readFileSync(fileURLToPath(destination), "utf8") !== output) {
    throw new Error("Native campaign vectors differ from web. Regenerate and check the Kotlin results.");
  }
} else writeFileSync(fileURLToPath(destination), output);
console.log(`Verified ${vectors.length} full web campaigns (${vectors.reduce((n, v) => n + v.weeks.length, 0)} weeks).`);
