import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createGame } from "../../../src/engine/setup";
import { choiceAvailable, resolveDebate } from "../../../src/engine/events";
import { computeResult } from "../../../src/engine/voteModel";
import { EVENTS_BY_ID, GENERIC_DEBATES, HISTORICAL_EVENTS } from "../../../src/content/events";

const vectors = [];
for (const [scenario, deck] of Object.entries(HISTORICAL_EVENTS)) {
  const debates = scenario === "2020"
    ? [...deck, ...GENERIC_DEBATES, ...["debate_1", "vp_debate", "debate_final"].map(id => EVENTS_BY_ID[id])]
    : deck;
  for (const event of debates.filter(event => event.isDebate)) {
    for (const player of ["dem", "rep"] as const) {
      // Low readiness exercises locked options and meltdowns; prepared tickets
      // exercise every trait-gated response, including asymmetric VP debates.
      for (const readiness of [10, 95]) {
        const seed = `interactive:${scenario}:${event.id}:${player}:${readiness}`;
        const initial = createGame({ seed, scenario, playerCandidate: player, difficulty: "normal" });
        initial.turn = 4;
        Object.keys(initial.candidates[player].traits).forEach(key => {
          initial.candidates[player].traits[key as keyof typeof initial.candidates.dem.traits] = readiness;
        });
        initial.pendingEvents = ["dem", "rep"].map(forCandidate => ({ eventId: event.id, forCandidate: forCandidate as "dem" | "rep" }));
        for (const choice of event.choices.filter(choice => choiceAvailable(initial, player, choice))) {
          const game = structuredClone(initial);
          const debate = resolveDebate(game, event, { [player]: choice.id });
          const result = computeResult(game);
          vectors.push({ scenario, seed, player, readiness, eventId: event.id, choiceId: choice.id,
            debate, resources: game.resources, salience: game.salience, fired: game.firedEventIds,
            pending: game.pendingEvents, ev: result.electoralVotes, share: result.popularShare });
        }
      }
    }
  }
}
if (!vectors.some(v => v.debate.meltdown) || !vectors.some(v => v.debate.winner === "tie")) {
  throw new Error("Debate fixtures must cover a tie and a meltdown.");
}
const destination = new URL("../shared/src/commonTest/kotlin/com/lakesidegames/electioneer/engine/DebateWebVectors.kt", import.meta.url);
const output = `// Generated by apps/native/scripts/export-debate-vectors.ts. Do not edit.\npackage com.lakesidegames.electioneer.engine\n\ninternal val DEBATE_WEB_VECTORS = listOf(\n${vectors.map(v => `    """${JSON.stringify(v)}"""`).join(",\n")}\n).joinToString(",", "[", "]")\n`;
if (process.argv.includes("--check")) {
  if (readFileSync(fileURLToPath(destination), "utf8") !== output) throw new Error("Native debate fixtures differ from web. Regenerate and verify interactive answers.");
} else writeFileSync(fileURLToPath(destination), output);
console.log(`Verified ${vectors.length} interactive web debate answers across ${Object.keys(HISTORICAL_EVENTS).length} elections.`);
